version: '3'

services:
  ui-port-80:
    container_name: server-home-page
    hostname: plex-server
    image: dennisstine/media-server-home
    volumes:
      - /etc/letsencrypt/live/minininja.dev/fullchain.pem:/etc/letsencrypt/live/minininja.dev/fullchain.pem
      - /etc/letsencrypt/live/minininja.dev/privkey.pem:/etc/letsencrypt/live/minininja.dev/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
