version: '3'

services:
  ninjaflix-ui:
    container_name: ninjaflix-ui
    hostname: plex-server
    image: dennisstine/ninjaflix
    volumes:
      - /etc/letsencrypt/live/minininja.dev/fullchain.pem:/etc/letsencrypt/live/minininja.dev/fullchain.pem
      - /etc/letsencrypt/live/minininja.dev/privkey.pem:/etc/letsencrypt/live/minininja.dev/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
